Feature/task1
DariaKozh/Storage pull request #3
Opened 2024-04-18 08:57 UTC by DariaKozh

2024-04-21 18:31 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "Feature/task1". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 18:47 UTC, GUR-ok requested changes

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/StorageApplication.java
> +@EnableTransactionManagement
Сможешь объяснить зачем тут @EnableTransactionManagement? без нее работает?

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/aspect/ExecutionTimeAspect.java
> +        Object result = joinPoint.proceed();
Если joinPoint.proceed(); бросит исключение время замереется?
Мб try {
            return joinPoint.proceed();
        } finally {
			вывести время

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/aspect/TransactionAspest.java
> +                System.out.println("!!!НАЧАЛО ТРАНЗАКЦИИ");
sout не используем в боевом закоммиченном коде. нужно через логирование

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/aspect/TransactionAspest.java
> +                startTime = System.currentTimeMillis();
старт таймера начинается от тела метода или от начала коммита транзакции?

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/model/Product.java
> +    private BigDecimal price;
хорошо бы это было сделать отдельным фиксом.

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +        try {
connection и writer поместить в try with resource

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +            connection = DriverManager.getConnection(url,
вместо инжекта урлов и паролей лучше сразу заинжектить DataSource или EntityManagerFactory и из них получить connection

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +            ResultSet rs = stmt.executeQuery("SELECT  *  FROM products");
SELECT  *  FROM products FRO UPDATE

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +            connection.close();
Connection -> creates and automatically closes -> Statement
Statement -> creates and automatically closes -> ResultSet
а connection у нас будет автоматом клозится блоком try-with-resource

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +        String query = "SELECT price FROM products WHERE id = ?";
миллион лишних селектов. у тебя есть resultSetб ты из него же сразу можешь получить старую цену.. а ты беершь айди и идешь опять за ценой. это странно

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +            e.printStackTrace();
connection по дефолту коммитит каждый стейтмент на апдейт.
тебе нужно вначале выставить connection.autocimmit(false)
вручную коммитить после того как все батчи прогнали,
вручную делать роллбэк, если перехвачено исключение

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/OptimizedProductPriceScheduler.java
> +            e.printStackTrace();
попробуй првоерить остановкой приложения в процессе работы шедулера, изменилась ли только часть данных

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/scheduling/SimpleProductPriceScheduler.java
> +            List<Product> products = productRepository.findAllProducts().get();
productRepository.findAllProducts().get() ? там же пустой список возвращается если ниче нет. не нужно тут так делать и бросать NotFoundException

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/CategoryServiceImpl.java
> +    @Transactional
readOnly = true тогда. операция на извлечение.

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/CategoryServiceImpl.java
> +    @Transactional
а зачем?

2024-04-21 18:47 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/ProductServiceImpl.java
> +    @Transactional
Везде просто так Transactional?

2024-04-23 21:07 UTC, DariaKozh commented on src/main/java/com/github/dariakozh/storage/StorageApplication.java
> +@EnableTransactionManagement
убрала

2024-04-23 21:13 UTC, DariaKozh commented on src/main/java/com/github/dariakozh/storage/aspect/TransactionAspest.java
> +                startTime = System.currentTimeMillis();
от начала коммита

2024-04-25 13:46 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/aspect/TransactionAspest.java
> +                startTime = System.currentTimeMillis();
хотелось бы от начала тела метода до конца коммита

2024-04-25 13:47 UTC, GUR-ok approved these changes

2024-04-28 19:21 UTC, merged