Task4: add order service
DariaKozh/Storage pull request #8
Opened 2024-05-09 19:42 UTC by DariaKozh

![Визуализация отношений в таблицах](https://github.com/DariaKozh/Storage/assets/104941264/037e3b57-0fb8-4547-b4fb-0f8e766612dc)

2024-05-12 08:07 UTC, GUR-ok requested changes

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/model/Order.java
> +    private String deliveryAddress;
здесь нужно будет добавить добавить связь oneToMany с заказанными товарами, о причинах будет в сервисе

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        if (products.isEmpty()) {
а если только 1 не нашли из 10? убрать это условие. ненайденные товары будут ловиться дальше

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +            Integer orderQuantity = orderDto.getProducts().stream().filter
стрим в стриме дает квадратичную алгоритмическую сложность. 
нужно собрать хэшмапу, чтобы избежать квадратичной сложности при проходе цикл-в-цикле.
Когда получим все интересующие нас товары создаем мапу
```
        final Map<UUID, ProductEntity> productMap = productList.stream()
                .collect(Collectors.toMap(ProductEntity::getId, Function.identity()));
```    
Потом стримом проходишься по товарам из запроса, внутри обращаясь к этой мапе и создавая orderedProduct

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +            Integer orderQuantity = orderDto.getProducts().stream().filter
и вот когда будешь обращаться к хэшмапе и там не найдешь товар, то и будет брсоаться NotFoundException("Товары не найдены на складе"); причем с айдишником

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        Order order = new Order(UUID.randomUUID(), customer, Status.CREATED,
UUID.randomUUID() - так не делаем. нужно сделать генератор хибернейта, чтобы сам присваивал айди

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        productRepository.saveAll(products);
productInOrderRepository.saveAll(productInOrders);
        productRepository.saveAll(products);
        породят кучу лишних запросов. кидал в чат
 Для решения как раз и нужно добавить связь в orderEntity

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +            Integer orderQuantity = productOrderDtos.stream().filter
тут аналогичная история цикл в цикле

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        productRepository.saveAll(products);
скинь скрин запросов хибернейта в бд

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        productRepository.saveAll(products);
тут будет много лишних запросов. нужен один сейв ордера только и все. остальное должно каскадно сейвится

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        List<ProductInOrder> productInOrderList = productInOrderRepository.getProductInOrderByOrderId(orderId);
мы запрашиваем ордер, запрашиваем отдельно productInOrderListб потом еще и products. Если бы была свзяь oneToMany, все эти уровни вложенности можно запросить одним запросом
примерно таким
```
    @Query("""
                select o from OrderEntity o
                left join fetch o.orderedProducts ps
                left join fetch ps.product p
                where o.id = :orderId
           """)
    Optional<OrderEntity> findByIdFetchOrderedProducts(UUID orderId);
```

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        Order order = orderRepository.findById(orderId).orElseThrow(() -> new NotFoundException("Заказ с id = " +
.orElseThrow на новую строку

2024-05-12 08:07 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +            ProductInOrder product = productInOrderList.stream().filter(productInOrder -> productInOrder
после того как запустили стрим все промежуточные операции (например .filter) с новой строки

2024-05-18 13:45 UTC, DariaKozh commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        productRepository.saveAll(products);
2024-05-18T16:32:03.287+03:00 DEBUG 12892 --- [nio-8080-exec-2] org.hibernate.SQL                        : 
    insert 
    into
        storage_order
        (customer_id, delivery_address, status, id) 
    values
        (?, ?, ?, ?)
2024-05-18T16:32:03.380+03:00 DEBUG 12892 --- [nio-8080-exec-2] org.hibernate.SQL                        : 
    insert 
    into
        order_product
        (price, quantity, order_id, product_id) 
    values
        (?, ?, ?, ?)
2024-05-18T16:32:03.408+03:00 DEBUG 12892 --- [nio-8080-exec-2] org.hibernate.SQL                        : 
    insert 
    into
        order_product
        (price, quantity, order_id, product_id) 
    values
        (?, ?, ?, ?)
2024-05-18T16:32:03.446+03:00 DEBUG 12892 --- [nio-8080-exec-2] org.hibernate.SQL                        : 
    update
        product 
    set
        category_id=?,
        description=?,
        is_available=?,
        item=?,
        last_modified_date=?,
        price=?,
        quantity=?,
        title=? 
    where
        id=?
2024-05-18T16:32:03.462+03:00 DEBUG 12892 --- [nio-8080-exec-2] org.hibernate.SQL                        : 
    update
        product 
    set
        category_id=?,
        description=?,
        is_available=?,
        item=?,
        last_modified_date=?,
        price=?,
        quantity=?,
        title=? 
    where
        id=?

2024-05-18 13:45 UTC, DariaKozh commented on src/main/java/com/github/dariakozh/storage/service/OrderServiceImpl.java
> +        productRepository.saveAll(products);
в заказе 2 товара было

2024-05-23 04:46 UTC, GUR-ok commented on src/main/java/com/github/dariakozh/storage/model/ProductInOrderKey.java
> +import lombok.*;
импорты не схлопываем, настрой идею плз

2024-05-23 04:47 UTC, GUR-ok approved these changes
Апрув

2024-05-25 13:05 UTC, merged